services:
  play:
    build:
      context: .
      dockerfile: Dockerfile
    image: play
    container_name: play
    env_file:
      - .env
    ports:
      - "9000:9000"
    expose:
      - "9000"
    networks:
      - play-docker
    tty: true
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0.29
    container_name: mysql
    env_file:
      - ./db/env.mysql
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./db/my.cnf
        target: /etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - play-docker
    restart: always

  web:
    image: nginx:1.22.0
    container_name: web
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - play-docker
    restart: always

  redis:
    image: redis:7.0.0-alpine
    container_name: redis
    volumes:
      - type: volume
        source: redis-data
        target: /data
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - play-docker
    restart: always

volumes:
  mysql-data:
  redis-data:

networks:
  play-docker:
    driver: bridge
